language: groovy
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- chmod +x ./gradlew
script:
- "./gradlew --no-daemon check"
deploy:
  provider: script
  script: "./gradlew clean assemble bintrayUpload --debug"
  on:
    tags: true
env:
  global:
  - secure: KkW7tCXr9vhDi1NjIU+4bZKgXqxBRkDYSvhRE2YYpxBYd3OX970MeaO8oP7PS0EwpZtKYH5YMYuLuAzo9l+T0y7960FYy+rol815yPg/bP4ALCo9Wcs0daV5MLvP6Ogjr7Y3Fmw06P5x1B8pxCPYJ/xSvd5aehEzRPhZRlnlb9ehNiA0ABeyIFrakhFGKiMTU+OeuULs21Hkfk8dNSUNoKUV9GuDOV4kP9OIpLDLEkhxhsBBfyHv33AU2Bn0ImK7qk/43bbd1Jb2Zx6PlKXxqSp4snPMM3PFH/I7QZyr+qYI5TgyHaEZox/H/ivlvTBuBK8+xpkAwrFNq5B2EQ2OZVVKXOeczMLOLghrfqCkiL6vJ33KJ9V0vQAeZV/4uMcsvvD7u3lTNkmpvwNdF+AySXZDqhU/TMkuJogjIMxwj/kmHCv9hJ5T3w9OTlmzKuVm2oRwOSxNNJiMYTimAn42nVDpAfH1hP2TBVKssn+hAaiIVJvl/OubC/gKmtzsAOLSx+/Uus7Gr4FHo7SubBW+kY35TD9uwSYg4H0wBLbYQJvHmtO9baXoTHWK3r5ehU5Z4fsoATkGz8clI8yo18VGwUgbXKFtk8kRzgDEHDYtamT6l4xM1lpxbJtW0cO/Flrja0aw76TXMzUmiS0mldyOHIGSXEsh16bFb/lWzhYmX+E=
  - secure: LKNj4ifCdnIAeTRuc/39yc4Od/ZDFzD7HxCQR0Efk8K4cZqsXtJYCEIVpoOZuM7xg4nLtzfcYDkaxodK9LR7KVZuo1C3ehtmgUQ9jsBV2GoJFvFVV7ipHT0iMdc50Nc6hRApXIJpLRrGJNZpKuAUpHC3YIJXhEaszFxEBX4CMgzWyVNPM6YUPoax6D3oZdjfLonUtAj/1TjYwORRr30o7iXspaWYyZetvrV0e9wj0aTwRJJq+XAaLuJsJXXCwGxLnd6UUocnORJ9Ip/ZhMTp77iGXNVwp57yUxvtgjQC7qvb/6FhkTYM7HALBs7paPkCp+Dc4rHCZC0/+FHTOAvayd1erPQZxk3MJaW5i//YMmrcKJloOpfa+gSsYJccWVrZ4Q1U4IKPK6mFYjINR5squXfEEIOft+7VYLiL5RrPLAIFBvCvlbcU2UOPG1Rwr3nQQ12rX+eA5FA6YYk+un6xDMikvm9XEw4784LWZ+wxz5pxrVw1siFAAlhhcXye5fxH2H/tk5AXZdp4vSSuDRmiJ+4CxnJLbyMqqQ/wKNW0Es3gBlxinHCwBZdP3vQUKY2K9zbRmG0KRwGYrsjXKuAe7e37vq9hkRf3m3XEVw5uG9a/F1thze189m3qipwNQbd+lSwNUUY1eGkcX3p+JkjYoXs+3rtbY9K+TY0/jqr7onM=
